name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # запускается каждый день в полночь
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: LORDx0001
          outputs: |
            ./github-contribution-grid-snake.svg
            ./github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "github-contribution-grid-snake.svg"
